### ISSUE TITLE
GPS Case Bolt Holes

### ISSUE THREAD

**Issue by alexzhou707** [ARK-Electronics/ARK_RTK_GPS#1]
The board has M2 clearance holes (2.2mm), but it appears that the case was designed for M2.5 screws and nuts. The thru hole is 2.5mm and the pocket is a 4.5mm hex, whereas they should be 2.2mm and 4mm, respectively.

**Comment by AlexKlimaj** [comment]
I added extra clearance for 3d printing. Here is the model if you want to customize it.
https://a360.co/3Dkk9tt

**Comment by alexzhou707** [comment]
I think that may be a bit too much clearance—the M2 nuts (4mm hex) just spin in place and are impossible to tighten. On the other hand, the pockets in the V6X case are a 5.2mm hex, which provides a better fit for an M2.5 nut (5mm hex).

Thank you for the file, though.

**Comment by alexzhou707** [comment]
I think that may be a bit too much clearance—the M2 nuts (4mm hex) just spin in place and are impossible to tighten. On the other hand, the pockets in the V6X case are a 5.2mm hex, which provides a better fit for an M2.5 nut (5mm hex).

Thank you for the file, though.
